[conf]
default-lang = "fi"

[lang.en]
aalto = "Aalto University"
sci = "School of Science"
program = "Master’s Programme in Engineering Physics"
type = "Report"
summary = "Abstract"
author = "Author"
title = "Title"
date = "Date"
nof_pages = "No. of pages"
major = "Major"
course_code = "Course code"
main_teacher = "Main teacher"
supervisor = "Supervisor"
keywords = "Keywords"
language = "Language"
subtitle = "Subtitle"
january = "January"
february = "February"
march = "March"
april = "April"
may = "May"
june = "June"
july = "July"
august = "August"
september = "September"
october = "October"
november = "November"
december = "December"
list_of_abbreviations = "List of Abbreviations"
abstract = "write your abstract here"

[lang.fi]
aalto = "Aalto-yliopisto"
sci = "Perustieteiden korkeakoulu"
program = "Master’s Programme in Engineering Physics"
type = "Raportti"
summary = "TIIVISTELMÄ"
author = "Tekijä"
title = "Työn nimi"
date = "Päiväys"
nof_pages = "Sivumäärä"
major = "Pääaine"
course_code = "Koodi"
main_teacher = "Vastuuopettaja"
supervisor = "Työn ohjaaja"
keywords = "Avainsanat"
language = "Kieli"
subtitle = "Ala otsikko"
january = "tammikuuta"
february = "helmikuuta"
march = "maaliskuuta"
april = "huhtikuuta"
may = "toukokuuta"
june = "kesäkuuta"
july = "heinäkuuta"
august = "elokuuta"
september = "syyskuuta"
october = "lokakuuta"
november = "marraskuuta"
december = "joulukuuta"
list_of_abbreviations = "Lyhenteet"
"abstract" = "kirjoita tiivistelmä tähän"
