[conf]
default-lang = "fi"

[lang.en]
aalto = "Aalto University"
sci = "School of Science"
program = "Master’s Programme in Engineering Physics"
type = "Report"
level = "Level"
summary = "Abstract"
author = "Author"
title = "Title"
date = "Date"
nof_pages = "Pages"
major = "Major"
course_code = "Course code"
main_teacher = "Main teacher"
supervisor = "Supervisor"
keywords = "Keywords"
language = "Language"
languagename = "English"
subtitle = "Subtitle"
january = "Jan"
february = "Feb"
march = "Mar"
april = "Apr"
may = "May"
june = "Jun"
july = "Jul"
august = "Aug"
september = "Sep"
october = "Oct"
november = "Nov"
december = "Dec"
list_of_abbreviations = "List of Abbreviations"
abstract = "write your abstract here"

[lang.fi]
aalto = "Aalto-yliopisto"
sci = "Perustieteiden korkeakoulu"
program = "Master’s Programme in Engineering Physics"
type = "Raportti"
level = "Työn laji"
summary = "TIIVISTELMÄ"
author = "Tekijä"
title = "Työn nimi"
date = "Päiväys"
nof_pages = "Sivuja"
major = "Pääaine"
course_code = "Koodi"
main_teacher = "Vastuuopettaja"
supervisor = "Työn ohjaaja"
keywords = "Avainsanat"
language = "Kieli"
languagename = "englanti"
subtitle = "Ala otsikko"
january = "1."
february = "2."
march = "3."
april = "4."
may = "5."
june = "6."
july = "7."
august = "8."
september = "9."
october = "10."
november = "11."
december = "12."
list_of_abbreviations = "Lyhenteet"
"abstract" = "kirjoita tiivistelmä tähän"
